### ISSUE TITLE
Option to download remote files

### ISSUE THREAD

**Issue by brohlson** [datocms/gatsby-source-datocms#139]
It would be nice to have a `gatsby-config` flag or the ability to pass a resolver function for easily being able to download remote media files from DatoCMS instead of always serving URLs from your CDN.   Is that sort of functionality on the roadmap for this plugin?

**Comment by stefanoverna** [comment]
Not at the moment Chase!

—
Stefano Verna

DatoCMS

--- original message ---
On January 27, 2021, 9:40 PM GMT+1 notifications@github.com wrote:



It would be nice to have a gatsby-config flag or the ability to pass a resolver function for easily being able to download remote media files from DatoCMS instead of always serving URLs from your CDN. Is that sort of functionality on the roadmap for this plugin?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by GordanRatkovic** [comment]
@brohlson did you manage to figure this out on your own? I was looking into something similar...
