### ISSUE TITLE
Package vulnerabality issue

### ISSUE THREAD

**Issue by kalkson** [datocms/gatsby-source-datocms#148]
The issue is not fixable with audit and it caused by gatsby-source-datocms:

![image](https://user-images.githubusercontent.com/56680144/109971117-25a06600-7cf6-11eb-9eec-5d93dcef15df.png)

**Comment by stefanoverna** [comment]
We'll look into that, thanks for reporting!

—
Stefano Verna

DatoCMS

--- original message ---
On March 4, 2021, 2:31 PM GMT+1 notifications@github.com wrote:



The issue is not fixable with audit and it caused by gatsby-source-datocms:


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by stefanoverna** [comment]
Should be fixed now!
