### ISSUE TITLE
Auto-generated URL paths for SEO meta tags and navigation

### ISSUE THREAD

**Issue by sedubois** [datocms/gatsby-source-datocms#31]
It's super neat that DatoCMS auto-generates the various _seoMetaTags, thank you 🙂 This currently seems to exclude `og:url`, but it would be very helpful to have this auto-generated too as it's quite a hassle to rebuild this as a Gatsby node field calculated based on a slug property added to the different models (i.e. custom logic in Gatsby-node, etc).

Would it be possible for DatoCMS to auto-generate a unique localized path for the different resources? This should have the flexibility e.g. that resources in the default language don't have a prefix while others are prepended with a language prefix (e.g /fr, /es, ...).

This path would then be readily available to populate SEO meta tags, to create `<link rel="alernate">` to other language versions of the same page, and to build the various navigation links within our websites.

**Comment by matjack1** [comment]
Sorry for not having replied earlier here.

We don't think this should be part of the Gatsby plugin because DatoCMS doesn't know about how you structure your pages and would be impossible to know if you have a page under another and how you would like to have the slug constructed.

Would be useful to do that in the API so that we could have a mapping betwen records and URLs, giving us the possibility to link a CMS record with a preview, but that would mean a lot of changes also on the backend before arriving here.

So I'm closing this for now, as we are already tracking the preview idea here: https://github.com/datocms/product-roadmap/issues/8 and https://github.com/datocms/product-roadmap/issues/156
