### ISSUE TITLE
html attributes returns null in multiple paragraph text field

### ISSUE THREAD

**Issue by fredmontet** [datocms/gatsby-source-datocms#51]
## Issue Description
Querying the html of a multiple paragraph text such as in the code block below doesn't work the same way for all the editors that can be set in the field setting in the presentation tab.

```
{
  allDatoCmsBlogPost {
    edges {
      node {
        excerptNode {
          childMarkdownRemark {
            html
            timeToRead
          }
        }
      }
    }
  }
}
```
I'm quite confused by the two different GraphQL syntax existing with DatoCMS i.e. the one usable in GraphiQL console and the one from the gatsby-source-datocms plugin. The default one is much more transparent I find...

**Comment by matjack1** [comment]
Yes @fredmontet you are right, the two syntaxes are different and it confuses quite a lot of people, but we had to comply to the Gatsby-style for the GraphQL queries, as it's what they have decided.

So yes, inside Gatsby you should check this syntax: https://github.com/datocms/gatsby-source-datocms#how-to-query

And so I recommend you to use the internal GraphQL explorer (e.g. http://localhost:8000/___graphql ) instead of the one hosted from DatoCMS ( https://graphql.datocms.com/graphiql ) so that you can check that your query syntax is correct.

I'm going to close the issue for now, but if I've misunderstood your problem feel free to reopen it.
