### ISSUE TITLE
Site spidering does not match page query

### ISSUE THREAD

**Issue by shenst1** [datocms/gatsby-source-datocms#56]
I have enabled site search and have logs that show how many pages and what the urls of my website are. However, they are quite different than what a query results in with the api. I can't seem to find any pattern for what is causing this. 
There are definitely unique pages I can visit on production that are not crawled but I need them to be. 

Spider says 32 pages crawled:
<img width="953" alt="Screen Shot 2019-05-14 at 1 19 18 PM" src="https://user-images.githubusercontent.com/3740533/57729760-d1715100-764b-11e9-98da-168927f9e07b.png">
Query says there are 76 pages on the site. 
<img width="857" alt="Screen Shot 2019-05-14 at 1 27 22 PM" src="https://user-images.githubusercontent.com/3740533/57729864-0aa9c100-764c-11e9-951f-ce43b08f1193.png">

**Comment by matjack1** [comment]
@shenst1 the crawler looks for links in the pages and follows them. So that might cause your issue.

Are you sure that all pages are reachable via links from the homepage?

Anyway, this doesn't look like a bug in this plugin, but rather in DatoCMS's internal search. So if the problem persists please reach me at support@datocms.com

**Comment by shenst1** [comment]
Yeah, wasn't sure where to report this issue. I did not know that was how the spider worked. thanks

**Comment by shenst1** [comment]
@matjack1 is there a way to add a manifest or something that would allow it to crawl other pages? Or is the index page the only way?
