### ISSUE TITLE
Very Slow 'build' and 'develop' times. Netlify deployments fail

### ISSUE THREAD

**Issue by dante-blitz** [datocms/gatsby-source-datocms#78]
Hi there,

We are experiencing very slow times when running deploy and build tasks. This is also causing Netlify deployments to fail as the deployment process exceeds the 15 minute time limit.

A little background info regarding our use case...

Our client has 26,000+ external news articles in their DatoCMS instance. Each record basically holds a title and an external url.

We do not generate individual gatsby pages for each article, rather we place them on landing pages (24 articles per page).

Since adding all 26,000 news articles to DatoCMS we have seen the develop and build tasks slow down significantly. This happened even before we created the landing pages, or ran any queries for the news articles.

The bottleneck happens on the following build tasks:

```
10:59:33 AM: success loading DatoCMS content — 715.684
10:59:55 AM: success source and transform nodes — 737.087
```

Are you able to provide any insight as to why the above build tasks are taking so long?

Do you know of any resolutions or workarounds?

Thanks in advance.

**Comment by dante-blitz** [comment]
https://github.com/gatsbyjs/gatsby/issues/17689

**Comment by matjack1** [comment]
thank you @dante-blitz really we don't have any workaround currently. It seems pretty big to me and I'm not sure how much faster we can make it.

We can surely change how we fetch data, using GraphQL instead of REST, but it's not going to come soon.

Meanwhile the only workaround that I can think of is to ask Netlify for longer builds :(

**Comment by dante-blitz** [comment]
Do you know why the build time increases just by adding all the items into your CMS? 

i.e. we don't touch them in Gatsby

I've also noticed that sometime the 2 steps outline above ('loading DatoCMS content' and 'success source and transform nodes') complete rather quickly. Any ideas as to why this happens sometimes? (I suspect it has something to do with caching)

**Comment by dante-blitz** [comment]
Here's an example... You can see a huge difference in the completion times...

```
5:43:51 PM: success loading DatoCMS content — 95.863
5:44:18 PM: success source and transform nodes — 122.330
```

**Comment by matjack1** [comment]
@dante-blitz even if you don't do anything in Gatsby with the records we have to build a data structure to hold them all and yes caching might help sometimes, but I guess in Netlify you cannot do that?

Anyway I'm sorry about that now but we cannot promise anything on this now.

I've added in our development backlog a task to move from REST API to GraphQL API for this plugin which could make things a bit faster, but I'm not even sure it would completely solve your issue here as we would still need to map our data to be used in Gatsby so we would need to try and see how much benefit we would get.

I'm closing this for now, but feel free to reopen or comment more if you feel so.
