### ISSUE TITLE
401 INVALID_SITE

### ISSUE THREAD

**Issue by dingyi** [datocms/gatsby-source-datocms#85]
When I run gatsby develop, it said:

```
"gatsby-source-datocms" threw an error while running the sourceNodes lifecycle:

401 INVALID_SITE (details: {})
```

but I still can query data from DatoCMS in http://localhost:8000/___graphql

How can I fix this error warning?

**Comment by matjack1** [comment]
@dingyi this is very strange! You say that in the GraphiQL you can see data, but can you query data also in your code? Is that only a wrong warning or are you having some issues?

**Comment by LluisArevalo** [comment]
Yes, I'm having the same problem when running `gatsby build`

**Comment by matjack1** [comment]
normally @dingyi @LluisArevalo this happens when you haven't specified the `DATO_API_TOKEN` either in your .env file or directly in the gatsby-config.js file. Can you please give me more details on how to reproduce the problem?

If you want to share your repo with me, either here if it's public or over support@datocms.com if it's private.

**Comment by matjack1** [comment]
thank you for the update @LluisArevalo !

**Comment by dingyi** [comment]
@matjack1 Thank you! I tried DATO_API_TOKEN and it works now!

**Comment by matjack1** [comment]
Excellent, thank you @dingyi for your feedback, I'm closing this for now then :)
